export const GET_TOP_MOVIES = "GET_TOP_MOVIES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_TOP_MOVIES_ERROR = "GET_TOP_MOVIES_ERROR";
export const SEARCH_MOVIES_ERROR = "SEARCH_MOVIES_ERROR";
export const MOVIE_DETAIL = "MOVIE_DETAIL";
export const MOVIE_DETAIL_ERROR = "MOVIE_DETAIL_ERROR";
